// ============================================================================
// lib/schema/transactionEvent.js
// Canonical ingestion contract for all payment rails.
//
// This schema is rail-agnostic by design. Any real PSP integration (UPI, card,
// wallet) maps its native payload to this shape via an adapter function.
// The fraud engine always scores a TransactionEvent — never a raw PSP payload.
//
// No raw PANs, VPAs, or account numbers are stored. Adapter functions must
// hash any PII before populating the `id` fields (see lib/crypto.js).
// ============================================================================

import { z } from 'zod';

// ─── Sub-schemas ─────────────────────────────────────────────────────────────

export const SenderSchema = z.object({
  /** Hashed/opaque sender identifier — NEVER raw PAN or VPA */
  id: z.string().min(1).max(128),
  /** Account age in days — used for new-account velocity signals */
  accountAgeDays: z.number().nonnegative().int().optional(),
  /** Rolling 30-day average transaction amount for this sender */
  avgTxnAmount30d: z.number().nonnegative().optional(),
});

export const ReceiverSchema = z.object({
  /** Hashed/opaque receiver identifier */
  id: z.string().min(1).max(128),
  /** True if sender has never transacted with this receiver */
  isNewPayee: z.boolean(),
});

export const DeviceSchema = z.object({
  /** Opaque device fingerprint (UA hash, canvas hash, etc.) */
  fingerprint: z.string().max(256).optional(),
  /** True if this device hasn't been seen for this sender before */
  isNewDevice: z.boolean(),
  /** ISO 3166-1 alpha-2 country code from IP geolocation */
  ipCountry: z.string().length(2).optional(),
});

export const LocationSchema = z.object({
  /** WGS84 latitude — used for haversine impossible-travel checks */
  lat: z.number().min(-90).max(90).optional(),
  /** WGS84 longitude */
  lng: z.number().min(-180).max(180).optional(),
  /** True if this location hasn't been seen for this sender */
  isNewLocation: z.boolean(),
});

// ─── Main schema ─────────────────────────────────────────────────────────────

export const TransactionEventSchema = z.object({
  /** UUID v4 — generated by the adapter or PSP */
  eventId: z.string().uuid(),

  /** ISO 8601 timestamp of when the transaction was initiated */
  timestamp: z.string().datetime({ offset: true }),

  /** Transaction amount in the minor or major unit — see currency */
  amount: z.number().positive('Amount must be positive'),

  /** ISO 4217 three-letter currency code (INR, USD, EUR, …) */
  currency: z.string().length(3).toUpperCase(),

  /** Payment rail that originated this transaction */
  rail: z.enum([
    'UPI',            // Unified Payments Interface (India)
    'CARD_PRESENT',   // Physical POS / EMV chip / contactless
    'CARD_NOT_PRESENT', // E-commerce / MOTO / recurring
    'WALLET',         // Digital wallets (PhonePe, Paytm, GPay balance)
    'NETBANKING',     // Direct bank debit via net banking portal
    'OTHER',          // Catch-all for custom rails
  ]),

  sender: SenderSchema,
  receiver: ReceiverSchema,
  device: DeviceSchema,
  location: LocationSchema,

  /**
   * Account balance AFTER this transaction settles (from PSP).
   * Used for amount_balance_ratio feature.
   * Omit if PSP does not expose balance.
   */
  balanceAfter: z.number().optional(),

  /**
   * Rail-specific extras. Validated by the adapter, never required by the
   * scoring engine. Examples: UPI ref ID, MCC code, 3DS result, terminal ID.
   * Never store raw PANs, CVVs, or VPAs here.
   */
  metadata: z.record(z.string(), z.unknown()).optional(),
});

// ─── Type exports (JSDoc for editor hints) ───────────────────────────────────

/**
 * @typedef {import('zod').infer<typeof TransactionEventSchema>} TransactionEvent
 * @typedef {import('zod').infer<typeof SenderSchema>} Sender
 * @typedef {import('zod').infer<typeof ReceiverSchema>} Receiver
 * @typedef {import('zod').infer<typeof DeviceSchema>} Device
 * @typedef {import('zod').infer<typeof LocationSchema>} Location_
 */

// ─── Validation helper ───────────────────────────────────────────────────────

/**
 * Parse and validate a raw object as a TransactionEvent.
 * Returns { success: true, data } or { success: false, errors }.
 *
 * @param {unknown} raw
 * @returns {{ success: true, data: TransactionEvent } | { success: false, errors: string[] }}
 */
export function parseTransactionEvent(raw) {
  const result = TransactionEventSchema.safeParse(raw);
  if (result.success) {
    return { success: true, data: result.data };
  }
  const errors = result.error.issues.map(
    (issue) => `${issue.path.join('.')}: ${issue.message}`
  );
  return { success: false, errors };
}

/**
 * Strict parse — throws a ZodError if invalid.
 * Use in server-side code where you want to propagate a 400 error.
 *
 * @param {unknown} raw
 * @returns {TransactionEvent}
 */
export function parseTransactionEventOrThrow(raw) {
  return TransactionEventSchema.parse(raw);
}
